version: "3.1"

services:
  ldap:
    image: openldap:almalinux
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "${OPENLDAP_VERSION:-2.5.13}"
    environment:
      DN: "dc=dgs,dc=net"
      PASSWD: "secret"
      NAME: "DGS Net"
    container_name: ldap
    hostname: ldap
    volumes:
      - usr-local:/usr/local

volumes:
  usr-local: