#!/usr/bin/env bash
set -euo pipefail
set -x

if [[ -e "/usr/local/etc/openldap/slapd.d/cn=config" ]]; then
  exit
fi

DN="${DN:-dc=my-domain,dc=com}"
DOMAIN=$(echo "${DN}" | awk -F= '{print $2}' | awk -F, '{print $1}')
NAME="${NAME:-My Domain}"
PASSWD="${PASSWD:-secret}"

for file in domain.ldif slapd.conf slapd.ldif; do
  sed -i "s/dc=my-domain,dc=com/${DN}/g" "$file"
  sed -i "s/my-domain/${DOMAIN}/g" "$file"
done

sed -i "s/secret/${PASSWD}/g" slapd.{ldif,conf}
sed -i "s/My Domain/${NAME}/g" domain.ldif

# Generate config based on slapd.ldiff
# /usr/local/sbin/slapadd -n 0 \
#   -F /usr/local/etc/openldap/slapd.d \
#   -l /usr/local/etc/openldap/slapd.ldif

# Generate config based on slapd.conf
slaptest -f slapd.conf -F slapd.d/